#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "${DOCKERFILE_PATH}" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f ${DOCKERFILE_PATH}"
fi

DOCKER_CONTENT_TRUST=1

docker build \
    --build-arg VERSION="20.2.0" \
    ${DOCKERFILE_PATH_ARG} -t ${IMAGE_NAME} .

echo "------ HOOK END - BUILD -------"
